#!/bin/bash

#Path to checkpoint file.
CHECKPOINT_PATH=$(pwd)/../../ML_Models/ShowAndTell/checkpoints/model.ckpt-5000000
echo ${CHECKPOINT_PATH}

#Vocabulary file generated by the preprocessing script.
VOCAB_FILE=$(pwd)/../../ML_Models/ShowAndTell/checkpoints/word_counts.txt

#JPEG image file to caption.
IMAGE_FILE=$1

# Build the inference binary.
cd ../../ML_Models/ShowAndTell/im2txt
bazel build -c opt //im2txt:run_inference

#Run inference to generate captions.
bazel-bin/im2txt/run_inference \
  --checkpoint_path=${CHECKPOINT_PATH} \
  --vocab_file=${VOCAB_FILE} \
  --input_files=${IMAGE_FILE}
