IMAGE_DIR = "/mydata/apache-tomcat/webapps/QIK_Image_Data/"
CHECKPOINT_PATH = "../ML_Models/ShowAndTell/checkpoints/"
VOCAB_FILE = "../ML_Models/ShowAndTell/checkpoints/word_counts.txt"
IMAGE_URL="http://localhost:8080/QIK_Image_Data/"
INDEX_ENGINE_URL = "http://localhost:8080/IndexEngine/postData?data="
THREAD_COUNT = 5
IMAGE_LIST_FILE="images.txt"
TOMCAT_LOC = "/mydata/apache-tomcat/webapps"
QIK_SCENES_PATH= TOMCAT_LOC + "/QIK_Scene_Data"
VIDEO_DIR = "/mydata/DatabaseVideos"
